---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: admin@kyma-project.io
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
    - dns01:
        webhook:
          groupName: acme.kyma-project.io
          solverName: kyma-dns
        # clouddns:
        #   project: sap-se-cx-kyma-goat
        #   serviceAccountSecretRef:
        #     name: dns-challenger
        #     key: gcloud-dns-admin.json                    
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: letsencrypt-crt
spec:
  secretName: kyma-goat-ga-tls
  dnsNames:
  - "*.kyma-goat.ga"
  issuerRef:
    name: letsencrypt-staging
    kind: Issuer
