---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-init-{{ .Release.Namespace }}
  labels:
    app: {{ include "dns-challenger.name" . }}
    chart: {{ include "dns-challenger.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    helm.sh/hook-delete-policy: "before-hook-creation"
    helm.sh/hook: pre-install
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create", "get", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-init-{{ .Release.Namespace }}
  labels:
    app: {{ include "dns-challenger.name" . }}
    chart: {{ include "dns-challenger.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    helm.sh/hook-delete-policy: "before-hook-creation"
    helm.sh/hook: pre-install
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-init-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: cert-manager-init-{{ .Release.Namespace }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-init-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "dns-challenger.name" . }}
    chart: {{ include "dns-challenger.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    helm.sh/hook-delete-policy: "before-hook-creation"
    helm.sh/hook: pre-install
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Release.Namespace }}
  name: cert-manager-init-{{ .Release.Namespace }}
  annotations:
    helm.sh/hook-delete-policy: "before-hook-creation"
    helm.sh/hook: pre-install
spec:
  template:
    spec:
      serviceAccountName: cert-manager-init-{{ .Release.Namespace }}
      containers:
      - name: kubectl
        image: bitnami/kubectl
        command: ["kubectl",  "apply", "--validate=false", "-f", "https://raw.githubusercontent.com/jetstack/cert-manager/release-0.12/deploy/manifests/00-crds.yaml"]
      restartPolicy: OnFailure
