# Default values for cert-manager-init.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: bitnami/kubectl
  tag: latest
  pullPolicy: IfNotPresent
